name: crowd_funding_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2
  infinite_scroll_pagination: ^3.1.0
  flutter_markdown: ^0.6.2
  font_awesome_flutter: ^9.1.0
  path: ^1.8.0
  dotted_border: ^2.0.0
  intl: ^0.17.0
  http: ^0.13.3
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  google_maps_flutter: ^2.0.6
  geolocator: ^7.3.1
  geocoding: ^2.0.0
  fluttertoast: ^8.0.7
  cached_network_image: ^3.1.0
  progress_hud: ^1.1.0
  flutter_spinkit: ^5.0.0
  flutter_summernote: ^1.0.0
  flutter_html: ^2.1.2
  share: ^2.0.4
  url_launcher: ^6.0.9
  dio: ^4.0.0
  carousel_slider: ^4.0.0
  webview_flutter: ^2.0.12
  badges: ^2.0.1
  easy_localization: ^3.0.0
  socket_io_client: ^1.0.1
  mime: ^1.0.0
  camera: 
  image_cropper: ^1.4.1
  image_picker: 
  path_provider: 
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.14
  integration_test:
    sdk: flutter
  build_runner: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
